spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/calendario_eventos
    username: postgres
    password: Sen@c2023
    driver-class-name: org.postgresql.Driver

<<<<<<< HEAD
  seguranca:
    segredo: "chave de acesso"
    tempo_validade: 5

=======
>>>>>>> 20594da14ce2d6cc9b904a468c0b85abe05e53e1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

<<<<<<< HEAD
=======
  security:
    jwt:
      secret: mySecretKey
      expiration: 86400000

  main:
    allow-circular-references: true

>>>>>>> 20594da14ce2d6cc9b904a468c0b85abe05e53e1
server:
  port: 8080
  servlet:
    context-path: /

cors:
  allowed-origins: http://localhost:5173

logging:
  level:
<<<<<<< HEAD
    com.eventos.calendario: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework.boot: INFO
=======
    com.eventos.calendario: DEBUG
    org.springframework.security: DEBUG
>>>>>>> 20594da14ce2d6cc9b904a468c0b85abe05e53e1
