spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/calendario_eventos
    username: postgres
    password: Sen@c2023
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    jwt:
      secret: mySecretKey
      expiration: 86400000

  main:
    allow-circular-references: true

server:
  port: 8080
  servlet:
    context-path: /

cors:
  allowed-origins: http://localhost:5173

logging:
  level:
    com.eventos.calendario: DEBUG
    org.springframework.security: DEBUG