spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/calendario_eventos
    username: postgres
    password: Sen@c2023
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080
  servlet:
    context-path: /

cors:
  allowed-origins: http://localhost:3000

logging:
  level:
    com.eventos.calendario: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework.boot: INFO